language: php

php:
  - 5.4
  - 5.5
  - 5.6

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm

env:
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.2
    - MAGENTO_VERSION=magento-mirror-1.8.1.0
    - MAGENTO_VERSION=magento-mirror-1.7.0.2

before_script:
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer install --no-interaction
  - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  
script:
  - php vendor/bin/parallel-lint --exclude vendor .
  - php vendor/bin/phpcs --standard=vendor/magento-ecg/coding-standard/Ecg,vendor/mygento/coding-standard/Mygento-Mage1 --ignore=lib .
  - php vendor/bin/phpcpd --exclude=vendor --exclude=lib .
  - php vendor/bin/phpdcd --exclude=vendor --exclude=lib .
  - php vendor/bin/phpmd . text vendor/mygento/coding-standard/Mygento-Mage1/phpmd.xml --exclude vendor,lib
  - curl -sSL https://raw.githubusercontent.com/mygento/hamster/master/setup.sh | bash
