language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: 7.0
    - php: hhvm

before_script:
  - composer self-update
  - composer install --no-interaction
  - php vendor/bin/phpcs --config-set ignore_warnings_on_exit 1
  
script:
  - php vendor/bin/parallel-lint --exclude vendor .
  - php vendor/bin/phpcs --standard=vendor/mygento/coding-standard/Mygento-Mage2 .
  - php vendor/bin/phpmd . text vendor/mygento/coding-standard/Mygento-Mage2/phpmd.xml --exclude vendor
